{
 "title": "STOCK_GIFI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Vue centrale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Nb de stock prêt à l'emploi",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "appdb",
     "rawSql": "SELECT SUM(`Nb de stock Mat prêt à lemploi`) FROM appdb.Articles LIMIT 50 "
    }
   ]
  },
  {
   "title": "%",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "appdb",
     "rawSql": "SELECT SUM(`Nb de stock Mat Fonctionnel`), SUM(`Nb de stock Mat prêt à lemploi`), SUM(`Nb de stock`) FROM appdb.Articles LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nb de stock fonctionnel & prêt à l'emploi",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "appdb",
     "rawSql": "SELECT SUM(`Nb de stock Mat Fonctionnel`), SUM(`Nb de stock Mat prêt à lemploi`) FROM appdb.Articles LIMIT 50 "
    }
   ]
  }
 ]
}